# Metadata about this component, to be used in the CMS
spec:
  structures: []
  label: Experience Card
  description: Experience card used for experience lists
  icon: wysiwyg
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  experience:
    title: ""
    subtitle: ""
    image: ""
    url: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  experience:
    title: Hello World
    subtitle: Lorem Ipsum
    image: https://placekitten.com/800/400
    url: /

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
