title: Kevin Carmona-Murphy
description: >-
  <p><strong>Senior Software Engineer</strong> with over 8 years of experience. Web App development using <strong>React, Ember.js and Typescript</strong> on the frontend, <strong>Rails, Django and Node.js</strong> on the backend. Believer in thorough <strong>automated tests</strong> and <strong>documentation.</strong></p>
social_media_share_image: /images/avatar.jpg
disqus-identifier:
google-analytics: